#!/usr/bin/env bash
# ============================================================
#  Reco-Nova v1.2 — Installer
#  Developer: Daniyal Shahid
# ============================================================
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${RED}"
echo "  ██████╗ ███████╗ ██████╗ ██████╗       ███╗   ██╗ ██████╗ ██╗   ██╗ █████╗ "
echo "  ██╔══██╗██╔════╝██╔════╝██╔═══██╗      ████╗  ██║██╔═══██╗██║   ██║██╔══██╗"
echo "  ██████╔╝█████╗  ██║     ██║   ██║█████╗██╔██╗ ██║██║   ██║██║   ██║███████║"
echo "  ██╔══██╗██╔══╝  ██║     ██║   ██║╚════╝██║╚██╗██║██║   ██║╚██╗ ██╔╝██╔══██║"
echo "  ██║  ██║███████╗╚██████╗╚██████╔╝      ██║ ╚████║╚██████╔╝ ╚████╔╝ ██║  ██║"
echo "  ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═════╝       ╚═╝  ╚═══╝ ╚═════╝   ╚═══╝  ╚═╝  ╚═╝"
echo -e "${NC}"
echo -e "  ${CYAN}Reconnaissance Intelligence Framework — Installer${NC}"
echo -e "  ${YELLOW}Developer: Daniyal Shahid  |  v1.2${NC}"
echo ""

# ── Step 1: Python version check ─────────────────────────────────
echo -e "${CYAN}[*] Checking Python version...${NC}"
if ! python3 -c "import sys; assert sys.version_info >= (3,9)" 2>/dev/null; then
  echo -e "${RED}[-] Python 3.9+ required. Please upgrade Python.${NC}"
  exit 1
fi
echo -e "${GREEN}[+] Python OK${NC}"
echo ""

# ── Step 2: System-level dependencies (for screenshot support) ────
# Firefox Headless and gowitness require Firefox browser
# and several shared libraries to capture screenshots.
echo -e "${CYAN}[*] Installing system-level screenshot dependencies...${NC}"
echo -e "    ${BLUE}(firefox-esr, firefox, libnss3, libgconf-2-4, libxi6, libxrandr2, fonts)${NC}"

if command -v apt-get &>/dev/null; then
  # Debian / Ubuntu / Kali Linux
  sudo apt-get update -qq
  sudo apt-get install -y --no-install-recommends \
    firefox-esr \
    firefox \
    libnss3 \
    libgconf-2-4 \
    libxi6 \
    libxrandr2 \
    libxss1 \
    libxcursor1 \
    libxcomposite1 \
    libasound2 \
    libxtst6 \
    libatk-bridge2.0-0 \
    libgtk-3-0 \
    libgbm1 \
    fonts-liberation \
    2>/dev/null && echo -e "${GREEN}[+] System dependencies installed${NC}" \
    || echo -e "${YELLOW}[!] Some system packages failed (non-fatal — screenshots may not work without Chrome)${NC}"
elif command -v pacman &>/dev/null; then
  # Arch Linux / BlackArch
  sudo pacman -S --noconfirm chromium nss libxi libxrandr 2>/dev/null \
    && echo -e "${GREEN}[+] System dependencies installed (pacman)${NC}" \
    || echo -e "${YELLOW}[!] pacman install incomplete — install chromium manually${NC}"
elif command -v dnf &>/dev/null; then
  # Fedora / RHEL
  sudo dnf install -y chromium nss libXrandr libXi 2>/dev/null \
    && echo -e "${GREEN}[+] System dependencies installed (dnf)${NC}" \
    || echo -e "${YELLOW}[!] dnf install incomplete — install chromium manually${NC}"
else
  echo -e "${YELLOW}[!] Package manager not detected. Install these manually:${NC}"
  echo -e "    ${YELLOW}chromium-browser libnss3 libgconf-2-4 libxi6 libxrandr2 libgtk-3-0 libgbm1${NC}"
fi
echo ""

# ── Step 3: Python pip dependencies ──────────────────────────────
echo -e "${CYAN}[*] Installing Python dependencies from requirements.txt...${NC}"
pip3 install -r requirements.txt --quiet --break-system-packages 2>/dev/null || \
pip3 install -r requirements.txt --quiet 2>/dev/null
echo -e "${GREEN}[+] Python dependencies installed${NC}"
echo ""

# ── Step 4: Force-reinstall bs4 to fix conflicts ────────────────
echo -e "${CYAN}[*] Force-reinstalling beautifulsoup4 (conflict prevention)...${NC}"
pip3 install beautifulsoup4 --break-system-packages --force-reinstall --quiet 2>/dev/null || true
echo -e "${GREEN}[+] bs4 reinstalled${NC}"
echo ""

# ── Step 5: Create 'reco-nova' alias with absolute path ────────────────
echo -e "${CYAN}[*] Creating 'reco-nova' alias with absolute path...${NC}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ALIAS_LINE="alias reco-nova='python3 \"${SCRIPT_DIR}/reco_nova.py\"'"

# Function to add alias to shell config
add_alias_to_config() {
    local config_file="$1"
    if [ -f "$config_file" ] && ! grep -q "reco-nova" "$config_file" 2>/dev/null; then
        echo "$ALIAS_LINE" >> "$config_file"
        echo -e "    ${GREEN}[+] Alias added to $config_file${NC}"
    elif [ -f "$config_file" ]; then
        echo -e "    ${YELLOW}[!] Alias already exists in $config_file${NC}"
    else
        echo -e "    ${YELLOW}[!] $config_file not found${NC}"
    fi
}

# Add to bashrc
add_alias_to_config "$HOME/.bashrc"

# Add to zshrc
add_alias_to_config "$HOME/.zshrc"

# Add to bash_profile (for macOS)
add_alias_to_config "$HOME/.bash_profile"

# Create a standalone alias file for easy sourcing
ALIAS_FILE="$HOME/.reco-nova-alias"
echo "# Reco-Nova Alias - Auto-generated by installer" > "$ALIAS_FILE"
echo "$ALIAS_LINE" >> "$ALIAS_FILE"
echo -e "    ${GREEN}[+] Standalone alias created: $ALIAS_FILE${NC}"

# Make executable
chmod +x "${SCRIPT_DIR}/reco_nova.py"
echo -e "${GREEN}[+] Alias creation complete${NC}"
echo ""

echo -e "  ${BLUE}Alias Information:${NC}"
echo -e "    ${YELLOW}Absolute path: ${SCRIPT_DIR}/reco_nova.py${NC}"
echo -e "    ${YELLOW}Alias command: reco-nova${NC}"
echo -e "    ${YELLOW}Standalone file: $ALIAS_FILE${NC}"
echo ""

# ── Done ──────────────────────────────────────────────────────────
echo -e "${GREEN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║          Installation Complete — v1.2                ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${CYAN}Next steps:${NC}"
echo -e "    ${YELLOW}source ~/.zshrc${NC}           (Kali/Zsh — load alias)"
echo -e "    ${YELLOW}source ~/.bashrc${NC}          (Bash — load alias)"
echo -e "    ${YELLOW}source ~/.bash_profile${NC}   (macOS Bash — load alias)"
echo -e "    ${YELLOW}source $ALIAS_FILE${NC}        (Standalone — load alias)"
echo -e "    ${YELLOW}reco-nova setup${NC}           (verify all dependencies)"
echo -e "    ${YELLOW}reco-nova -d example.com${NC}  (run first scan)"
echo ""
echo -e "  ${CYAN}Or run directly (no alias needed):${NC}"
echo -e "    ${YELLOW}python3 ${SCRIPT_DIR}/reco_nova.py -d example.com${NC}"
echo ""
echo -e "  ${BLUE}Alias troubleshooting:${NC}"
echo -e "    ${YELLOW}If alias doesn't work, run: source $ALIAS_FILE${NC}"
echo -e "    ${YELLOW}Or add to your current shell: eval \"$(cat $ALIAS_FILE)\"${NC}"
echo ""
echo -e "  ${BLUE}Screenshot Note:${NC}"
echo -e "    Firefox Headless is used for screenshots."
echo -e "    If screenshots fail, verify: ${YELLOW}firefox --version${NC}"
echo -e "    Fallback: gowitness uses individual URL processing"
echo ""